name: Recipe CI/CD
on:
  pull_request:
    branches: [master]
    tags:
      - 'v*'
  push:
    branches: [master]
    tags:
      - 'v*'

jobs:
  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
      # Make gradle executable
      - name: Make gradle executable
        run: chmod +x gradlew
      # Execute build with stacktrace
      - name: Build with gradle

  lint-check:
    name: 🔍 lint-checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint check
        run: ./gradlew lint

      - name: Generate Lint reports
        uses: actions/upload-artifact@v2
        with:
          name: lint-report.html
          path: app/build/reports/lint-results-debug.html

  generate-debug-apk:
    name: ⚙ Generate Debug apk
    needs: [build,lint-check]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/checkout@v3
        with:
          distribution: 'corretto'
          java-version: '11'
      - name: Build debug apk
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload debug apk
        uses: actions/upload-artifact@v1
        with:
          name: Recipe-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          gitReleaseNotes: true

  generating-release-apk: # Job to generate debug apk
    name: ⚙ Generate Release APK
    needs: [build,lint-check]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Build release apk
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload release apk
        uses: actions/upload-artifact@v1
        with:
          name: Recipe-release
          path: app/build/outputs/apk/release/app-release-unsigned.apk
          gitReleaseNotes: true

  create-release: # Job to create new github release and upload the generated file
    name: 🎉 Create release
    needs: [generating-release-apk]
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: Recipe-release

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: v${{github.run_number}}
          release_name: v${{github.run_number}}

      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: Recipe-release/app-release-unsigned.apk
          gitReleaseNotes: true
          asset_name: Recipe.apk
          asset_content_type: application/zip